# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:20.0.1
  amd64: ghcr.io/hassio-addons/base:20.0.1

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: CarConnectivity Edge"
  org.opencontainers.image.description: "Addon version of Carconnectivity Edge made by Till (see https://github.com/tillsteinbach/CarConnectivity) throught MQTT"
  org.opencontainers.image.source: "https://github.com/Pulpyyyy/carconnectivity-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"

args:
  AUDI_VERSION: "v0.3.0"
  SEAT_VERSION: "v0.6"
  SKODA_VERSION: "v0.12"
  VW_VERSION: "v0.10.4"
  VWNA_VERSION: "v0.1.15-b.2"
  TRONITY_VERSION: "v0.7.1"
  VOLVO_VERSION: "v0.1a2"
  ABRP_VERSION: "v0.8.1"
  MQTT_VERSION: "v0.10"
  MQTTHA_VERSION: "v0.6.4"
  WEBUI_VERSION: "v0.7.1"
  CC_VERSION: "v0.11.8"
