# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:18.1.4
  amd64: ghcr.io/hassio-addons/base:18.1.4

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: CarConnectivity Edge"
  org.opencontainers.image.description: "Addon version of Carconnectivity Edge made by Till (see https://github.com/tillsteinbach/CarConnectivity) throught MQTT"
  org.opencontainers.image.source: "https://github.com/Pulpyyyy/carconnectivity-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"

args:
  AUDI_VERSION: "v0.2.0"
  SEAT_VERSION: "v0.5"
  SKODA_VERSION: "v0.11"
  VW_VERSION: "v0.10"
  VWNA_VERSION: "v0.1.5"
  TRONITY_VERSION: "v0.7"
  VOLVO_VERSION: "v0.1a2"
  ABRP_VERSION: "v0.6"
  MQTT_VERSION: "v0.9"
  MQTTHA_VERSION: "v0.5.1"
  WEBUI_VERSION: "v0.6"
  CC_VERSION: "v0.11.1"
