# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:20.0.1
  amd64: ghcr.io/hassio-addons/base:20.0.1

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: CarConnectivity"
  org.opencontainers.image.description: "Addon version of Carconnectivity made by Till (see https://github.com/tillsteinbach/CarConnectivity) throught MQTT"
  org.opencontainers.image.source: "https://github.com/Pulpyyyy/carconnectivity-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"

args:
  AUDI_VERSION: "repository.json:}"
  SEAT_VERSION: "repository.json:}"
  SKODA_VERSION: "repository.json:}"
  VW_VERSION: "repository.json:}"
  VWNA_VERSION: "repository.json:}"
  TRONITY_VERSION: "repository.json:}"
  VOLVO_VERSION: "repository.json:}"
  ABRP_VERSION: "repository.json:}"
  MQTT_VERSION: "repository.json:}"
  MQTTHA_VERSION: "repository.json:}"
  WEBUI_VERSION: "repository.json:}"
  CC_VERSION: "repository.json:}"