name: Builder (2026)

on:
  workflow_call:
    inputs:
      addon:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [ "amd64", "aarch64" ]

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Get addon info
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ inputs.addon }}"

      - name: Check if image exists
        id: exist
        run: |
          TAG="${{ steps.info.outputs.version }}"
          ADDON="${{ inputs.addon }}"
          ARCH="${{ matrix.arch }}"
          NAMESPACE="pulpyyyy"

          URL="https://hub.docker.com/v2/repositories/${NAMESPACE}/${ADDON}-${ARCH}/tags/${TAG}/"

          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL")

          if [ "$STATUS" -eq 200 ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Build with HA Docker Builder
        if: steps.exist.outputs.exists == 'false'
        run: |
          docker run --rm --privileged \
            -v "${{ github.workspace }}:/data" \
            ghcr.io/home-assistant/amd64-builder:2026.03.2 \
              --addon \
              --${{ matrix.arch }} \
              --docker-hub docker.io \
              --image "pulpyyyy/${{ inputs.addon }}-${{ matrix.arch }}" \
              --docker-user "${{ secrets.DOCKERHUB_USERNAME }}" \
              --docker-password "${{ secrets.DOCKERHUB_TOKEN }}"
